### ISSUE TITLE
flashbios broken in 1.1.24

### ISSUE THREAD

**Issue by organicveggie** [protectli-root/protectli-firmware-updater#22]
TL;DR: Missing a comma in `flashli/configurations.py` between lines 257 and 258.

```
Traceback (most recent call last):
File "/home/kubuntu/Downloads/protectli-firmware-updater-main/./flashbios”, line 15, in <module>
from flashli import configurations, hardware
File "/home/kubuntu/Downloads/protectli-firmware-updater-main/flashli/configurations.py”, line 239
'vpd630': {
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

**Comment by jimbobjonesbob** [comment]
yes, broken.

please fix

**Comment by SergeyKonst3** [comment]
Apologies for a late response to this issue. 

The syntax has been fixed in the configuration.py file.

Please confirm that the issue has been resolved in version 1.1.25

**Comment by tux2bsd** [comment]
I was considering buying a Protecli product until I saw the issues on this project.  This public demonstration of Protectli's very poor issue handling skills leaves far too much to be desired...

**Comment by SergeyKonst3** [comment]
Our apologies for any issues this has caused.  Can you please clarify the exact issue so we can improve going forward?

**Comment by organicveggie** [comment]
@SergeyKonst3, while I can't speak for @tux2bsd, I believe we actually three separate, but related, issues:

1. An embarrassingly silly typo which totally broke the firmware updater. Should have been caught by unit testing, integration testing, or QA before being released. People can get nervous when they run into issues with something commonly used as a security appliance. And when the issue seems disturbingly simple, you start to wonder if they missed other simple issues.
2. Two weeks to respond is ... disappointing.
3. You didn't following typical GitHub etiquette when handling this in terms of managing issues and pull requests in GitHub:
3a. You ignored the pull request I sent to fix the issue: [pull/23](https://github.com/protectli-root/protectli-firmware-updater/pull/23). Here we 8 months later and nothing has happened. At the very least, you should have commented on the PR explaining that the underlying issue was already fixed and closed the the PR as obsolete.
3b. You don't need me to confirm this issue was fixed. When you commented the underlying code was updated, you should have included a reference to the commit which fixed it (so we could easily look at the fix). Then marked this issue as closed with a note saying I should reopen it if I continue having problems.

None of that gives outsiders confidence that Protectli is building high quality security products. Nor does it reassure people that Protectli is dedicated to opensource development.

Just my 2 cents.

**Comment by tux2bsd** [comment]
@organicveggie exactly right.  p.s. @organicveggie despite what's being discussed here do you like the product?  (I asked elsewhere but cannot be sure of any notifications github may or may not have sent).

@SergeyKonst3 a security product, or any product for that matter, cannot be neglected at its public face. Perhaps development in-house is very good but it is betrayed by public appearance.  Fix issues that can be fixed.  Close issues that go nowhere.  Deal with things promptly.  These are beginner level suggestions, it is perplexing to even need to make the point.

**Comment by SergeyKonst3** [comment]
@organicveggie and @tux2bsd  thank you for your feedback. We will reflect on your statements.
We have been working on  better release and testing procedures for this process. 
Sadly this issue did slip through and this is not acceptable and we apologize. Going forward we are going to improve how we handle issues and pull requests and better adhere to GitHub etiquette. 

Thank you for your feedback.

At this time we are going to close this issue. If anything comes up please reopen the issue.

**Comment by tux2bsd** [comment]
@SergeyKonst3 nice work on following up on these things, no need to apologize.  Perhaps make a weekly reminder to check on these github items then they won't be forgotten - life is busy, reminders are good.

**Comment by SergeyKonst3** [comment]
@tux2bsd Thank you for your kind words. Yes for sure,  we are currently working on setting up reminds.
