### ISSUE TITLE
command from readme is wrong for ubuntu 22.04.1

### ISSUE THREAD

**Issue by Corylus-Core** [protectli-root/protectli-firmware-updater#24]
"./flashbios" command is not working on "ubuntu 22.04.1". Getting an error saying "bash: ./flashbios: Permission denied".

"sudo python3 ./flashbios" does the trick. Hard to figure out for people who are not used to linux and the terminal.

**Comment by SergeyKonst3** [comment]
The permissions have been revised for the flashbios file.
Please try again and let us know if the issue has been resolved.

**Comment by Corylus-Core** [comment]
sorry for my late response.

i still had to use "sudo ./flashbios" on a FW2B.

**Comment by SergeyKonst3** [comment]
Sorry for the confusion, forgot to add the revision to the README.md file.
It has been updated to include using sudo with the script.
