### ISSUE TITLE
VP6650 compatibility

### ISSUE THREAD

**Issue by ethnt** [protectli-root/protectli-firmware-updater#35]
VP6650 does not seem to be supported, since the interfaces that Flashli requires (`enp1s0`) does not exist on the device (it provides `enp2s0f0`, `enp2s0f1`, `enp3s0`,  `enp4s0`, `enp5s0`, and `enp6s0`). Is VP6650 support going to be present eventually?

**Comment by SergeyKonst3** [comment]
Hello, 

Thank you for bringing this to our attention. 

Yes, there are plans to bring all VP6600 series support to Flashli (protectli-firmware-updater).

As coreboot is currently not available on VP4600 series, support has not yet been implemented. We expect the release of coreboot for the VP4600 series to be at the end of April. When coreboot is released that is also when the support for the VP4600 series will be implemented into Flashli (protectli-firmware-updater).

**Comment by Flash1232** [comment]
Now that the VP6600 series is supported via Flashli, is there a rough timeline when coreboot support will be available too? Thank you

**Comment by SergeyKonst3** [comment]
Hello,

Apologize for the late response. 
We are in the process of testing coreboot on the VP6600 series. The current estimated release time frame is early to mid September.

**Comment by SergeyKonst3** [comment]
Hello,
We have released coreboot for the VP6600 series and it has been added to Flashli version 1.1.44. 

At this time support for the VP6600 has been added and coreboot released. I am closing this issues at  this time. If there are any problems related to the VP6650 please feel free to reopen the issue.
