### ISSUE TITLE
Failure on V1210

### ISSUE THREAD

**Issue by danieldk** [protectli-root/protectli-firmware-updater#41]
```
Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Opened /dev/mtd0 successfully
Found Programmer flash chip "Opaque flash chip" (16384 kB, Programmer-specific) on internal.
Reading old flash chip contents... done.
Erasing and writing flash chip... linux_mtd_erase: MEMERASE ioctl call returned -1, error: Input/output error
Reading current flash chip contents... done. Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
No usable erase functions left.
FAILED!
Uh oh. Erase/write failed. Checking if anything has changed.
Reading current flash chip contents... done.
Apparently at least some data has changed.
Your flash chip is in an unknown state.
Get help on IRC (see https://www.flashrom.org/Contact) or mail
flashrom@flashrom.org with the subject "FAILED: <your board name>"!-------------------------------------------------------------------------------
DO NOT REBOOT OR POWEROFF!
BIOS Flash failed, is this script running with root permissions?
Please try again, but if problems persist, please contact Protectli.
TODO: Collect info and display instructions on how to submit a Github issue.
```

And now what 😨

**Comment by SergeyKonst3** [comment]
Hello danieldk,

Can you please provide some more information. 
What OS and version are you using ? Where you going from AMI to coreboot, AMI to AMI, coreboot to AMI? What version of Flashli are you using?

**Comment by danieldk** [comment]
I am flashing from Ubuntu Jammy using flashli v1.1.47. I originally did this because I wanted to flash coreboot (from AMI), which failed. Now I'm trying to flash AMI to try, but same error. (Haven't rebooted yet.)

**Comment by danieldk** [comment]
Tried the oldest flashlight version for the V1210 and now it still fails, but ends with a more hopeful message:

```
Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Opened /dev/mtd0 successfully
Found Programmer flash chip "Opaque flash chip" (16384 kB, Programmer-specific) on internal.
Reading old flash chip contents... done.
Erasing and writing flash chip... linux_mtd_erase: MEMERASE ioctl call returned -1, error: Input/output error
Reading current flash chip contents... done. Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
Looking for another erase function.
No usable erase functions left.
FAILED!
Uh oh. Erase/write failed. Checking if anything has changed.
Reading current flash chip contents... done.
Good, writing to the flash chip apparently didn't do anything.
This means we have to add special support for your board, programmer or flash
chip. Please report this to the mailing list at flashrom@flashrom.org or on
IRC (see https://www.flashrom.org/Contact for details), thanks!
```

**Comment by SergeyKonst3** [comment]
Thank you for providing that information. I am trying to look further as to why the erase function is not working as expected. 
It seems nothing was erased based on the second log you have sent. We are still working on implementing verification of the files. I am glad the system still boots. 

With AMI it can be harder to verify, as long as it boots it should be OK. If you are still worried about  your BIOS please feel free to reach out to our support team at [support@protectli.com](mailto:support@protectli.com). Please mention this github issue if you do. 

 We will try to investigate this issue further and post any findings here.

**Comment by danieldk** [comment]
Good news! I tried again and this time AMI BIOS flashed without issues. So I'll leave it as it is, knowing that it's now booting from a known-good firmware.

**Comment by danieldk** [comment]
> It seems nothing was erased based on the second log you have sent.

It seems though that after several attempts nothing was written anymore (the erase/write almost immediately finishes). I checked the source code for flashrom and the only thing it does is verify against the original contents. I guess that is useful to some extend, but didn't tell much in my case about the state of the BIOS. In the end I verified with `flashrom_v2 -v` against all BIOS versions that I could download from this GitHub repo and none of them verified. Luckily enough it was apparently in a good-enough state that I could still restart to do a full flash. The `-v` option was really handy in investigating.

> If you have a chance could you please provide the steps taken that allowed you to flash without any issue, it would help us to get a better idea of the issue and help us improve Flashli.

When it went wrong:

* Booted Arch Linux live USB (Ubuntu was initially giving me a hard time with the serial console).
* Installed dependencies.
* Flash failed.
* Made an Ubuntu 22.04 environment with debootstrap (since the error message does say: do not reboot the machine).
* chrooted into that with proc/sys/dev mounted. Technically, this should be identical to Ubuntu 22.04 with a newer kernel.
* Installed all needed dependencies (would be nice if the README to listed them).
* Flash

When it succeeded:

* Booten Ubuntu 22.04 (got console to work correctly this time after using `set gfxpayload=text` and adding `console=tty0 console=ttyS0,115200n8 nosplash` (`nosplash` is important to not get a lot of garbage).
* I couldn't find any way to boot in non-EFI mode, the instructions on the protectli site don't work (F11 etc. don't give a boot menu, but instead drop you in the AMI interface, where you can only select EFI boot options), but it seems to work nonetheless.
* Install missing dependencies.
* Flash successfully.

I am not sure if I just got unlucky the first time or whether somehow the Arch kernel/system configuration breaks things.

**Comment by danieldk** [comment]
Apparently I was feeling lucky today and tried flashing coreboot again with the successful procedure from yesterday and it worked 🎉. So, Ubuntu 22.04 seems to have done the trick.

**Comment by SergeyKonst3** [comment]
Thank you very much for providing detailed steps and suggestions.
 
We will review this further and see what other safeguards we can implement to stop something like this from happening.
At this time I would suspect there is a possible issue with Arch kernel/ system configuration and flashrom, as it  worked in Ubuntu 22.04. Further investigation is needed to find the root cause of the failure. 
We will try to revise the README to include more information. 

I am glad you were able to flash coreboot to your device. 
If you are experiencing any more issues please feel free to reach out to us, add more to this issue or open another issue.
